### ISSUE TITLE
Campos ainda ficam preenchidos com CEP inválido

### ISSUE THREAD

**Issue by rjslegall** [LimaJonas/magento-autocomplete-cep-br#3]
Olá!

Notamos este comportamento que pode causar confusão para os clientes. Pode nos ajudar?

Quando o cliente preenche um CEP válido os campos são preenchidos corretamente.
Porém, se em seguida, ele preencher um CEP incorreto (acredite isso acontece) os campos
ainda continuam preenchidos.

Logicamente quando o campo CEP é inválido temos o retorno:
GET https://brasilapi.com.br/api/cep/v1/77777-777?_=1627136733518 404

Mas os campos ainda continuam preenchidos com os dados anteriores.
Alguns clientes mais distraídos, com certeza não irão se atentar e continuar a compra.
Seria possível, quando tivermos um retorno 404 os campos serem automaticamente apagados?
Ou outra solução para corrigir este problema?

Obrigado

**Comment by LimaJonas** [comment]
Bom dia,

Uma solução simples para isso seria o JQuery apagar os campos caso api
retorne vazia. Algo simples como "$('input[name="street[0]"]').val() ou
text()". No momento não estou com meu computador para resolver isso. Mas
assim que possível darei uma olhada.

Obrigado por se interessar pelo projeto.

Em sáb, 24 de jul de 2021 11:56, rjslegall ***@***.***>
escreveu:

**Comment by rjslegall** [comment]
Obrigado pelo retorno Jonas!
Como não entendo muito de JQuery vou aguardar sua implementação.

Sobre a outra questão de endereço de entrega e cobrança, acha que dá para solucionar?

**Comment by LimaJonas** [comment]
implementado na atualização

**Comment by rjslegall** [comment]
A Solução funcionou bem. Obrigado!
